project "Remora.xcodeproj"
scheme "Remora"

devices [
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
]

languages ["en-US"]

output_directory "./fastlane/screenshots"
clear_previous_screenshots true
override_status_bar true

only_testing ["RemoraUITests/RemoraUITests/testCaptureAppStoreScreenshots"]
skip_testing ["RemoraTests"]
